name: Testing cub3D
run-name: Source code

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  compile:
    name: Compiling project
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Installing dependencies
        run: sudo apt-get install -y make
      
      - name: Compiling project
        run: make

