name: Init cub3D
run-name: Init cub3D

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  clean_repo:
    name: Clean repo
    runs-on: ubuntu-latest
    steps:
      - name: Clean objects
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y make

      - name: Script run
        run: ./scripts/clear_repo.sh
  
  norminette:
    name: Running norm
    runs-on: ubuntu-latest
    steps:
      - name: Binding env
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt update && sudo apt install python3-setuptools pipx
      
      - name: Install norminette
        run: pipx install norminette && pipx ensurepath
      
      - name: Running norminette
        run: norminette src/ include/ lib/

# concurrency 
# regles pour dev / main