name: Init cub3D

on:
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  clean_repo:
    name: Clean repo
    runs-on: ubuntu-latest
    steps:
      - name: Clean objects
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y make

      - name: Script run
        run: ./scripts/clear_repo.sh

# concurrency 
# regles pour dev / main